// src/pages/content/components/BlockDialog.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import Button from '../../../components/Button.vue'
import Input from '../../../components/Input.vue'
import { CLICK_ITEM_ACTION, emitter, OPEN_SETTING } from '../modules/emitter'
import { useEmitter } from '../composables/useEmitter'
import Header from './Header.vue'
import Radio from '../../../components/Radio.vue'
import { type Nullish } from '../../../types/Nullish'
import Dialog from '../../../components/Dialog.vue'
import SearchLinkSection from './SearchLinkSection.vue'
import { useMatchedRules } from '../composables/useMatchedRules'
import MatchedRulesSection from './MatchedRulesSection.vue'
import { appendRule, removeRule, replaceRule } from '../../../modules/ruleStorageAction'
import EditRuleDialog from './EditRuleDialog.vue'
import { type RuleType } from '../../../modules/rule'

const isOpened = ref(false)
function open () { isOpened.value = true }
function close () { isOpened.value = false }

const type = ref<'job' | 'company' | null>(null)

const jobTitle = ref<Nullish<string>>(null)
const companyName = ref<Nullish<string>>(null)

const jobTitleDraft = ref('')
const companyNameDraft = ref('')

useEmitter(CLICK_ITEM_ACTION, (payload) => {
  open()
  type.value = null

  jobTitle.value = payload.jobTitle
  companyName.value = payload.companyName

  jobTitleDraft.value = payload.jobTitle ?? ''
  companyNameDraft.value = payload.companyName ?? ''
})

function openSetting () {
  close()
  emitter.emit(OPEN_SETTING)
}

async function submit () {
  close()
  if (type.value === 'job') {
    await appendRule('jobTitle', jobTitleDraft.value)
  }
  if (type.value === 'company') {
    await appendRule('companyName', companyNameDraft.value)
  }
}

const isSubmitDisabled = computed(() => !(
  (type.value === 'job' && jobTitleDraft.value.trim()) ||
  (type.value === 'company' && companyNameDraft.value.trim())
))

const { matchedRules } = useMatchedRules({ companyName, jobTitle })

const editRuleDialogRef = ref<InstanceType<typeof EditRuleDialog> | null>(null)

async function handleEditRule (type: RuleType, rule: string) {
  try {
    const response = await editRuleDialogRef.value?.request(type, rule)
    if (!response) return

    if (response?.type === 'remove') {
      await removeRule(type, rule)
    } else if (response?.type === 'edit') {
      await replaceRule(type, rule, response.newRule)
    }
  } catch (err) {}
}
</script>

<template>
  <Dialog closeOnClickOutside :open="isOpened" @close="close">
    <div v-if="isOpened" class="flex flex-col gap-4">
      <Header />
      <div class="flex flex-col gap-4">
        <div class="flex items-center gap-2">
          <Radio v-model="type" value="company" />
          <Input
            v-model="companyNameDraft"
            label="公司名稱"
            @focus="type = 'company'"
          />
        </div>
        <div class="flex items-center gap-2">
          <Radio v-model="type" value="job" />
          <Input
            v-model="jobTitleDraft"
            label="職缺名稱"
            @focus="type = 'job'"
          />
        </div>
      </div>

      <MatchedRulesSection
        :matchedRules="matchedRules"
        @edit="handleEditRule"
      />

      <div class="flex flex-wrap items-center justify-end gap-2">
        <button
          class="underline"
          type="button"
          @click="openSetting"
        >
          管理關鍵詞
        </button>

        <div class="flex-1" />

        <Button type="button" @click="close">關閉</Button>
        <Button
          color="primary"
          :disabled="isSubmitDisabled"
          type="button"
          @click="submit"
        >
          封鎖
        </Button>
      </div>

      <template v-if="companyName">
        <hr class="border-neutral-800">
        <SearchLinkSection :companyName="companyName" />
      </template>
    </div>
  </Dialog>
  <EditRuleDialog ref="editRuleDialogRef" />
</template>

// src/pages/content/components/BlockDialog.tsx
import { useCallback, useState } from 'react'
import { type Nullish } from '../../../types/Nullish'
import { CLICK_ITEM_ACTION, emitter, OPEN_SETTING } from '../modules/emitter'
import { useEmitter } from '../hooks/useEmitter'
import { appendRule, removeRule, replaceRule } from '../../../modules/ruleStorageAction'
import { useMatchedRules } from '../hooks/useMatchedRules'
import { Dialog } from '../../../components/Dialog'
import { Header } from './Header'
import { Radio } from '../../../components/Radio'
import { Input } from '../../../components/Input'
import { Button } from '../../../components/Button'
import { SearchLinkSection } from './SearchLinkSection'
import { MatchedRulesSection } from './MatchedRulesSection'
import { type RuleType } from '../../../modules/rule'
import { EditRuleDialog, type EditRuleDialogState } from './EditRuleDialog'

export function BlockDialog () {
  const [isOpened, setIsOpened] = useState(false)

  function open () { setIsOpened(true) }
  function close () { setIsOpened(false) }

  const [type, setType] = useState<'job' | 'company' | null>(null)

  const [jobTitle, setJobTitle] = useState<Nullish<string>>(null)
  const [companyName, setCompanyName] = useState<Nullish<string>>(null)

  // TODO: refactor with RHF
  const [jobTitleDraft, setJobTitleDraft] = useState('')
  const [companyNameDraft, setCompanyNameDraft] = useState('')

  useEmitter(CLICK_ITEM_ACTION, useCallback((payload) => {
    open()

    setType(null)

    setJobTitle(payload.jobTitle)
    setCompanyName(payload.companyName)

    setJobTitleDraft(payload.jobTitle ?? '')
    setCompanyNameDraft(payload.companyName ?? '')
  }, []))

  function openSetting () {
    close()
    emitter.emit(OPEN_SETTING)
  }

  async function submit () {
    close()
    if (type === 'job') {
      await appendRule('jobTitle', jobTitleDraft)
    }
    if (type === 'company') {
      await appendRule('companyName', companyNameDraft)
    }
  }

  const isSubmitDisabled = !(
    (type === 'job' && jobTitleDraft.trim()) ||
    (type === 'company' && companyNameDraft.trim())
  )

  const { matchedRules } = useMatchedRules({ companyName, jobTitle })

  const [editRuleDialogState, setEditRuleDialogState] =
    useState<EditRuleDialogState | null>(null)

  async function handleEditRule (type: RuleType, rule: string) {
    setEditRuleDialogState({ type, rule })
  }

  return (
    <>
      <Dialog closeOnClickOutside open={isOpened} onClose={close}>
        {isOpened && (
          <div className="flex flex-col gap-4">
            <Header />
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-2">
                <Radio
                  checked={type === 'company'}
                  onChange={(checked) => {
                    if (checked) setType('company')
                  }}
                />
                <Input
                  label="公司名稱"
                  value={companyNameDraft}
                  onChange={setCompanyNameDraft}
                  onFocus={() => { setType('company') }}
                />
              </div>
              <div className="flex items-center gap-2">
                <Radio
                  checked={type === 'job'}
                  onChange={(checked) => {
                    if (checked) setType('job')
                  }}
                />
                <Input
                  label="職缺名稱"
                  value={jobTitleDraft}
                  onChange={setJobTitleDraft}
                  onFocus={() => { setType('job') }}
                />
              </div>
            </div>

            <MatchedRulesSection
              matchedRules={matchedRules}
              onEdit={handleEditRule}
            />

            <div className="flex flex-wrap items-center justify-end gap-2">
              <button
                className="underline"
                type="button"
                onClick={openSetting}
              >
                管理關鍵詞
              </button>

              <div className="flex-1" />

              <Button type="button" onClick={close}>關閉</Button>
              <Button
                color="primary"
                disabled={Boolean(isSubmitDisabled)}
                type="button"
                onClick={submit}
              >
                封鎖
              </Button>
            </div>

            {companyName && (
              <>
                <hr className="border-neutral-800" />
                <SearchLinkSection companyName={companyName} />
              </>
            )}
          </div>
        )}
      </Dialog>

      <EditRuleDialog
        state={editRuleDialogState}
        onResponse={async (response) => {
          if (!editRuleDialogState) return
          setEditRuleDialogState(null)

          if (response?.action === 'remove') {
            await removeRule(
              editRuleDialogState.type,
              editRuleDialogState.rule
            )
          } else if (response?.action === 'edit') {
            await replaceRule(
              editRuleDialogState.type,
              editRuleDialogState.rule,
              response.newRule
            )
          }
        }}
      />
    </>
  )
}
