// src/pages/content/components/Header.vue
<script setup lang="ts">
import { faGear } from '@fortawesome/free-solid-svg-icons'
import { OPEN_OPTIONS_PAGE_MESSAGE_NAME } from '../../../modules/constants'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

function openOptions () {
  chrome.runtime.sendMessage(OPEN_OPTIONS_PAGE_MESSAGE_NAME)
}
</script>

<template>
  <div class="flex items-center gap-3">
    <div
      class="h-10 w-10 bg-contain bg-center bg-no-repeat"
      :style="{ backgroundImage: 'var(--taiwan-company-blocker-icon)' }"
    />
    <div class="text-lg font-medium">封鎖此職缺或公司</div>

    <div class="flex-1" />

    <button
      class="group px-2"
      title="設定"
      type="button"
      @click="openOptions"
    >
      <div class="duration-500 group-hover:rotate-90">
        <FontAwesomeIcon :icon="faGear" />
      </div>
    </button>
  </div>
</template>

// src/pages/content/components/Header.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { OPEN_OPTIONS_PAGE_MESSAGE_NAME } from '../../../modules/constants'
import { faGear } from '@fortawesome/free-solid-svg-icons'

function openOptions () {
  chrome.runtime.sendMessage(OPEN_OPTIONS_PAGE_MESSAGE_NAME)
}

export function Header () {
  return (

    <div className="flex items-center gap-3">
      <div
        className="h-10 w-10 bg-contain bg-center bg-no-repeat"
        style={{ backgroundImage: 'var(--taiwan-company-blocker-icon)' }}
      />
      <div className="text-lg font-medium">封鎖此職缺或公司</div>

      <div className="flex-1" />

      <button
        className="group px-2"
        title="設定"
        type="button"
        onClick={openOptions}
      >
        <div className="text-lg duration-500 group-hover:rotate-90">
          <FontAwesomeIcon icon={faGear} />
        </div>
      </button>
    </div>
  )
}
