// src/pages/popup/components/EnableSwitch.vue
<script setup lang="ts">
import { nanoid } from 'nanoid'

defineProps<{
  modelValue: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

const id = nanoid()

function handleChange (event: Event) {
  emit('update:modelValue', (event.target as HTMLInputElement).checked)
}
</script>

<template>
  <label class="flex cursor-pointer select-none items-center" :for="id">
    <div class="relative">
      <input
        :id="id"
        :checked="modelValue"
        class="peer sr-only"
        type="checkbox"
        @change="handleChange"
      >
      <div
        class="h-5 w-14 rounded-full transition-colors duration-300"
        :class="modelValue ? 'bg-red-500' : 'bg-neutral-700'"
      />
      <div
        class="absolute -top-1 left-0 flex h-7 w-7 items-center justify-center rounded-full bg-neutral-300 transition duration-300 peer-checked:translate-x-full"
      >
        <span
          class="h-4 w-4 rounded-full transition-colors duration-300"
          :class="modelValue ? 'bg-red-500' : 'bg-neutral-400'"
        />
      </div>
    </div>
  </label>
</template>

// src/pages/popup/components/EnableSwitch.tsx
import { useId } from 'react'
import { cn } from '../../../modules/cn'

export function EnableSwitch ({ value, onChange, ...restProps }: {
  value: boolean
  onChange: (value: boolean) => void
  'data-testid': string
}) {
  const id = useId()

  return (
    <label
      className="flex cursor-pointer select-none items-center"
      htmlFor={id}
      {...restProps}
    >
      <div className="relative">
        <input
          checked={value}
          className="peer sr-only"
          id={id}
          type="checkbox"
          onChange={(event) => {
            onChange(event.target.checked)
          }}
        />
        <div
          className={cn(
            'h-5 w-14 rounded-full transition-colors duration-300',
            value ? 'bg-red-500' : 'bg-neutral-700'
          )}
        />
        <div
          className="absolute -top-1 left-0 flex h-7 w-7 items-center justify-center rounded-full bg-neutral-300 transition duration-300 peer-checked:translate-x-full"
        >
          <span
            className={cn(
              'h-4 w-4 rounded-full transition-colors duration-300',
              value ? 'bg-red-500' : 'bg-neutral-400'
            )}
          />
        </div>
      </div>
    </label>
  )
}
