// src/pages/popup/components/Statistic.tsx
import { type PropsWithChildren } from 'react'
import { cn } from '../../../modules/cn'

export function Statistic ({ name, muted, children, className }: PropsWithChildren<{
  name: string
  muted?: boolean
  className?: string
}>) {
  return (
    <div className={cn('flex flex-col', className)}>
      <div className="text-neutral-500">{name}</div>

      <div className={cn('text-xl font-medium', { 'text-neutral-600': muted })}>
        {children ?? '-'}
      </div>
    </div>
  )
}

// src/pages/popup/components/Statistic.vue
<script setup lang="ts">
defineProps<{
  name: string
  value: unknown
  muted?: boolean
}>()
</script>

<template>
  <div class="flex flex-col">
    <div class="text-neutral-500">{{ name }}</div>
    <div
      class="text-xl font-medium"
      :class="{ ' text-neutral-600': muted }"
    >
      {{ value ?? '-' }}
    </div>
  </div>
</template>
