// src/components/options/BlockMethodOptions.tsx
import { useChromeStorage } from '../../hooks/useChromeStorage'
import { blockMethods, formatBlockMethod } from '../../modules/BlockMethod'
import { BLOCK_METHOD_KEY } from '../../modules/storage'
import { Radio } from '../Radio'
import { Title } from '../Title'

export function BlockMethodOptions () {
  const [blockMethod, setBlockMethod] = useChromeStorage(BLOCK_METHOD_KEY)

  const options = blockMethods.map((value) => ({
    label: formatBlockMethod(value),
    value,
  }))

  return (
    <div className="flex flex-col gap-4">
      <Title>封鎖模式</Title>

      <div className="flex gap-6">
        {options.map(({ value, label }) => (
          <Radio
            key={value}
            checked={blockMethod === value}
            onChange={(checked) => {
              if (checked) {
                setBlockMethod(value)
              }
            }}
          >
            {label}
          </Radio>
        ))}
      </div>
    </div>
  )
}

// src/pages/options/components/BlockMethodOptions.vue
<script setup lang="ts">
import { computed } from 'vue'
import Radio from '../../../components/Radio.vue'
import { useChromeStorage } from '../../../composables/useChromeStorage'
import { blockMethods, formatBlockMethod } from '../../../modules/BlockMethod'
import { BLOCK_METHOD_KEY } from '../../../modules/storage'

import Title from './Title.vue'

const blockMethod = useChromeStorage(BLOCK_METHOD_KEY)

const options = computed(() => blockMethods.map((value) => ({
  label: formatBlockMethod(value),
  value,
})))
</script>

<template>
  <div class="flex flex-col gap-4">
    <Title>封鎖模式</Title>

    <div class="flex gap-6">
      <Radio
        v-for="{ value, label } in options"
        :key="value"
        v-model="blockMethod"
        :value="value"
      >
        {{ label }}
      </Radio>
    </div>
  </div>
</template>
