// src/pages/options/components/DatabaseItem.vue
<script setup lang="ts">
import { type IconDefinition } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

withDefaults(defineProps<{
  icon: IconDefinition
  active?: boolean
}>(), {})
</script>

<template>
  <div
    class="flex w-full items-center gap-2 rounded-lg p-2 text-start"
  >
    <div
      class="flex w-8 justify-center"
      :class="{ 'text-green-600': active }"
    >
      <FontAwesomeIcon :icon="icon" />
    </div>

    <div class="flex min-w-0 flex-1 flex-col px-2">
      <div
        class="truncate"
        :class="{ 'font-bold text-green-600': active }"
      >
        <slot name="title" />
      </div>

      <div class="truncate text-xs text-neutral-500">
        <slot name="content" />
      </div>
    </div>

    <div class="ml-auto flex">
      <slot name="action" />
    </div>
  </div>
</template>

// src/pages/options/components/DatabaseItem.tsx
import { type IconDefinition } from '@fortawesome/fontawesome-svg-core'
import { cn } from '../../../modules/cn'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { type ReactNode } from 'react'

export function DatabaseItem ({ icon, active, title, content, action }: {
  icon: IconDefinition
  active?: boolean

  title: ReactNode
  content?: ReactNode
  action?: ReactNode
}) {
  return (
    <div
      className="flex w-full items-center gap-2 rounded-lg p-2 text-start"
    >
      <div
        className={cn('flex w-8 justify-center', { 'text-green-600': active })}
      >
        <FontAwesomeIcon icon={icon} />
      </div>

      <div className="flex min-w-0 flex-1 flex-col px-2">
        <div className={cn('truncate', { 'font-bold text-green-600': active })}>
          {title}
        </div>

        <div className="truncate text-xs text-neutral-500">
          {content}
        </div>
      </div>

      <div className="ml-auto flex">
        {action}
      </div>
    </div>
  )
}
