// src/components/Editor.tsx
import CodeMirror from '@uiw/react-codemirror'
import { type Nullish } from '../types/Nullish'
import { useMemo } from 'react'
import { EditorView } from '@codemirror/view'
import { rulesLanguage } from '../modules/codeMirror'
import { codeMirrorTheme } from '../modules/codeMirrorTheme'

interface EditorProps {
  value: Nullish<string>
  onChange?: (value: string) => void
  disabled?: boolean
  height?: number | 'auto'
  lineWrapping?: boolean
}

export function Editor ({
  value,
  onChange,
  disabled,
  height = 300,
  lineWrapping,
}: EditorProps) {
  const extensions = useMemo(() => [
    rulesLanguage,
    codeMirrorTheme,
    ...(lineWrapping ? [EditorView.lineWrapping] : []),
  ], [lineWrapping])

  return (
    <CodeMirror
      editable={!disabled}
      extensions={extensions}
      height={typeof height === 'string' ? height : `${height}px`}
      indentWithTab={false}
      theme="none"
      value={value ?? undefined}
      onChange={onChange}
    />
  )
}

// src/components/Editor.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Codemirror } from 'vue-codemirror'
import { EditorView } from '@codemirror/view'
import { rulesLanguage } from '../modules/codeMirror'
import { codeMirrorTheme } from '../modules/codeMirrorTheme'
import { type Nullish } from '../types/Nullish'

const props = withDefaults(defineProps<{
  modelValue: Nullish<string>
  disabled?: boolean
  height?: number | 'auto'
  lineWrapping?: boolean
}>(), {
  height: 350,
})

defineEmits<{
  'update:modelValue': [value: string]
}>()

const extensions = computed(() => [
  rulesLanguage,
  codeMirrorTheme,
  ...(props.lineWrapping ? [EditorView.lineWrapping] : []),
])
</script>

<template>
  <Codemirror
    :disabled="disabled"
    :extensions="extensions"
    :indentWithTab="false"
    :modelValue="modelValue ?? undefined"
    :style="{ height: typeof height === 'string' ? height : `${height}px` }"
    @update:modelValue="$emit('update:modelValue', $event)"
  />
</template>
