// src/components/OverlayDialog.tsx
import { type PropsWithChildren, type SyntheticEvent, useLayoutEffect, useRef } from 'react'
import { useScrollLock } from '../hooks/useScrollLock'

type OverlayDialogProps = PropsWithChildren<{
  open?: boolean
  closeOnClickOutside?: boolean
  onClose?: () => void
}>

export function OverlayDialog ({
  open,
  closeOnClickOutside,
  onClose,
  children,
}: OverlayDialogProps) {
  // TODO: Extract me into a hook
  const dialogRef = useRef<HTMLDialogElement | null>(null)
  useScrollLock(open)

  function handleClickDialog (event: SyntheticEvent) {
    if (!closeOnClickOutside) return
    if (event.target !== dialogRef.current) return
    onClose?.()
  }

  useLayoutEffect(() => {
    if (open) {
      dialogRef.current?.showModal()
    } else {
      dialogRef.current?.close()
    }
  }, [open])

  return (
    <dialog
      ref={dialogRef}
      className="m-0 overflow-auto border-none p-0 outline-none backdrop:bg-neutral-900/50"
      onClick={handleClickDialog}
      onClose={onClose}
    >
      <div className="fixed right-0 top-0 h-full w-[700px] max-w-full">
        {children}
      </div>
    </dialog>
  )
}

// src/components/OverlayDialog.vue
<script setup lang="ts">
import { useScrollLock } from '../composables/useScrollLock'
import { onMounted, ref, watch } from 'vue'

const props = withDefaults(defineProps<{
  open?: boolean
  closeOnClickOutside?: boolean
}>(), {
  open: false,
  closeOnClickOutside: false,
})

const emit = defineEmits<{
  'close': []
}>()

const dialogRef = ref<HTMLDialogElement | null>(null)

const isLocked = useScrollLock()

onMounted(() => {
  watch(() => props.open, (isOpened) => {
    isLocked.value = isOpened
    if (isOpened) {
      dialogRef.value?.showModal()
    } else {
      dialogRef.value?.close()
    }
  }, { immediate: true })
})

function close () {
  emit('close')
}

function handleClickDialog (event: Event) {
  if (!props.closeOnClickOutside) return
  if (event.target !== dialogRef.value) return
  close()
}
</script>

<template>
  <dialog
    ref="dialogRef"
    class="m-0 overflow-auto border-none p-0 outline-none backdrop:bg-neutral-900/50"
    @click="handleClickDialog"
    @close="close"
  >
    <div class="fixed right-0 top-0 h-full w-[700px] max-w-full">
      <slot />
    </div>
  </dialog>
</template>
